import React, { useState } from 'react';
import { Mail, CheckCircle2, Eye, Send, Sparkles, RefreshCw, X } from 'lucide-react';
import { EmailLog } from '../types';

interface EmailsViewProps {
  emailLogs: EmailLog[];
}

const TYPE_META: Record<string, { color: string; bg: string; label: string }> = {
  application_received: { color: '#4f46e5', bg: 'rgba(99,102,241,0.08)',   label: 'Application Received' },
  shortlisted:          { color: '#0284c7', bg: 'rgba(2,132,199,0.08)',    label: 'Shortlisted'           },
  assessment_invitation:{ color: '#d97706', bg: 'rgba(217,119,6,0.08)',    label: 'Assessment Invite'     },
  interview_scheduled:  { color: '#7c3aed', bg: 'rgba(139,92,246,0.08)',   label: 'Interview Scheduled'   },
  offer_letter:         { color: '#059669', bg: 'rgba(5,150,105,0.08)',    label: 'Offer Letter'          },
  rejection:            { color: '#dc2626', bg: 'rgba(220,38,38,0.08)',    label: 'Rejection Notice'      },
};

function getTypeMeta(type: string) {
  const key = Object.keys(TYPE_META).find(k => (type || '').toLowerCase().includes(k));
  return key ? TYPE_META[key] : { color: '#64748b', bg: 'rgba(100,116,139,0.08)', label: type || 'Notification' };
}

export const EmailsView: React.FC<EmailsViewProps> = ({ emailLogs }) => {
  const [preview, setPreview] = useState<EmailLog | null>(null);

  const sent = emailLogs.filter(l => l.status === 'sent').length;
  const types = new Set(emailLogs.map(l => l.email_type || l.template_name || '')).size;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>

      {/* ── Banner ─────────────────────────────────────────────── */}
      <div className="page-banner brand" style={{ position: 'relative' }}>
        <div style={{ position: 'relative', zIndex: 1, display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 24 }}>
          <div>
            <div className="banner-eyebrow"><Sparkles size={12} /> Zero-Touch Communication</div>
            <h2 className="banner-title">Automated Notification Audit Trail</h2>
            <p className="banner-desc">
              Complete audit log of all system-triggered emails: Application receipts, Shortlistings, Assessment invitations, Interview calls, Offer letters & Rejections.
            </p>
          </div>
          <div style={{ display: 'flex', gap: 10, flexShrink: 0 }}>
            <div className="banner-stat"><span className="banner-stat-value">{sent}</span><span className="banner-stat-label">Emails Sent</span></div>
            <div className="banner-stat"><span className="banner-stat-value">{types}</span><span className="banner-stat-label">Templates</span></div>
          </div>
        </div>
      </div>

      {/* ── Delivery Mode Info Banner ──────────────────────────── */}
      <div style={{
        background: 'linear-gradient(135deg, rgba(99,102,241,0.06) 0%, rgba(14,165,233,0.06) 100%)',
        border: '1px solid rgba(99,102,241,0.18)',
        borderRadius: 12,
        padding: '16px 20px',
        display: 'flex',
        alignItems: 'flex-start',
        gap: 14
      }}>
        <div style={{
          width: 36,
          height: 36,
          borderRadius: 10,
          background: 'rgba(99,102,241,0.12)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          flexShrink: 0,
          marginTop: 2
        }}>
          <Mail size={18} color="#6366f1" />
        </div>
        <div style={{ flex: 1 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
            <span style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--text-primary)' }}>
              TalentIQ Notification Hub & Delivery Mode
            </span>
            <span className="badge" style={{ background: '#ecfdf5', color: '#059669', border: '1px solid #a7f3d0' }}>
              Active Outbox & Audit Log
            </span>
          </div>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', margin: 0, lineHeight: 1.5 }}>
            All automated notifications (Application acknowledgments, Shortlist notices, Assessment invites) are generated by TalentIQ and recorded in this audit trail.
            To dispatch these messages directly to real external inboxes (e.g. your personal Gmail), configure <code>SMTP_USER</code> and <code>SMTP_PASSWORD</code> in <code>backend/.env</code>.
          </p>
        </div>
      </div>

      {/* ── Table ──────────────────────────────────────────────── */}
      <div className="card">
        <div style={{ padding: '18px 24px', borderBottom: '1px solid var(--border-light)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <div style={{ width: 26, height: 26, borderRadius: 7, background: 'rgba(99,102,241,0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Mail size={13} color="#6366f1" />
            </div>
            <span style={{ fontSize: '0.92rem', fontWeight: 800, color: 'var(--text-primary)', letterSpacing: '-0.02em' }}>Email Delivery Log</span>
            <span className="badge" style={{ background: 'rgba(99,102,241,0.08)', color: '#4f46e5', border: '1px solid rgba(99,102,241,0.15)', marginLeft: 2 }}>
              {emailLogs.length} total
            </span>
          </div>
          <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Click any row to preview the email body</span>
        </div>

        <div style={{ overflowX: 'auto' }}>
          <table className="table">
            <thead>
              <tr>
                <th>Status</th>
                <th>Recipient</th>
                <th>Subject</th>
                <th>Trigger Event</th>
                <th>Delivered At</th>
                <th style={{ textAlign: 'right' }}>Action</th>
              </tr>
            </thead>
            <tbody>
              {emailLogs.map(log => {
                const m = getTypeMeta(log.email_type || log.template_name || '');
                return (
                  <tr key={log.id} onClick={() => setPreview(log)}>
                    <td>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                        {log.status === 'sent'
                          ? <CheckCircle2 size={14} color="#059669" />
                          : <RefreshCw size={14} color="#d97706" />}
                        <span style={{ fontSize: '0.78rem', fontWeight: 600, color: log.status === 'sent' ? '#059669' : '#d97706' }}>
                          {log.status === 'sent' ? 'Delivered' : 'Pending'}
                        </span>
                      </div>
                    </td>
                    <td>
                      <div style={{ fontWeight: 600, color: 'var(--text-primary)', fontSize: '0.875rem' }}>{log.recipient_email}</div>
                      {log.recipient_name && <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>{log.recipient_name}</div>}
                    </td>
                    <td>
                      <span style={{ fontSize: '0.82rem', color: 'var(--text-primary)', fontWeight: 500 }}>{log.subject}</span>
                    </td>
                    <td>
                      <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: '0.72rem', fontWeight: 600, padding: '3px 9px', borderRadius: 99, background: m.bg, color: m.color, border: `1px solid ${m.color}20` }}>
                        {m.label}
                      </span>
                    </td>
                    <td>
                      <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)', fontFamily: 'monospace' }}>
                        {new Date(log.sent_at || '').toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })}
                      </span>
                    </td>
                    <td style={{ textAlign: 'right' }}>
                      <button className="btn btn-secondary btn-sm" onClick={e => { e.stopPropagation(); setPreview(log); }}>
                        <Eye size={13} /> Preview
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>

          {emailLogs.length === 0 && (
            <div className="empty-state">
              <div className="empty-icon"><Send size={22} color="#6366f1" /></div>
              <div className="empty-title">No emails sent yet</div>
              <div className="empty-desc">Emails are triggered automatically when candidate stages are updated.</div>
            </div>
          )}
        </div>
      </div>

      {/* ── Preview Modal ───────────────────────────────────────── */}
      {preview && (
        <div className="modal-backdrop" onClick={() => setPreview(null)}>
          <div className="modal" style={{ maxWidth: 680, width: '100%', maxHeight: '90vh', display: 'flex', flexDirection: 'column' }} onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <div>
                <div className="modal-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <Mail size={16} color="#6366f1" />
                  <span>Email Dispatch Preview</span>
                  <span className="badge badge-indigo" style={{ fontSize: '0.72rem' }}>
                    {preview.body.includes('<html') ? 'Rich HTML Format' : 'Plaintext Format'}
                  </span>
                </div>
                <div className="modal-subtitle">Recipient: <strong style={{ color: '#4f46e5' }}>{preview.recipient_email}</strong> ({preview.recipient_name || 'Candidate'})</div>
              </div>
              <button className="btn btn-ghost btn-icon btn-sm" onClick={() => setPreview(null)}>
                <X size={18} color="var(--text-muted)" />
              </button>
            </div>
            <div className="modal-body" style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 12, overflowY: 'auto', padding: 20 }}>
              <div>
                <label className="form-label" style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-muted)' }}>Subject Line</label>
                <div style={{ padding: '8px 14px', background: 'var(--surface-subtle)', borderRadius: 8, border: '1px solid var(--border-default)', fontSize: '0.88rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                  {preview.subject}
                </div>
              </div>
              <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
                <label className="form-label" style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-muted)', marginBottom: 6 }}>
                  Rendered Email Content
                </label>
                {preview.body.includes('<html') || preview.body.includes('<!DOCTYPE') ? (
                  <iframe
                    title="Email Preview"
                    srcDoc={preview.body}
                    style={{
                      width: '100%',
                      height: 440,
                      border: '1px solid var(--border-default)',
                      borderRadius: 10,
                      background: '#f1f5f9'
                    }}
                  />
                ) : (
                  <div style={{ padding: 16, background: 'var(--surface-subtle)', borderRadius: 10, border: '1px solid var(--border-default)', fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: 1.7, whiteSpace: 'pre-wrap', maxHeight: 360, overflowY: 'auto' }}>
                    {preview.body}
                  </div>
                )}
              </div>
            </div>
            <div className="modal-footer" style={{ padding: '12px 20px', borderTop: '1px solid var(--border-default)' }}>
              <span style={{ flex: 1, fontSize: '0.75rem', color: 'var(--text-muted)', fontFamily: 'monospace' }}>
                Dispatched at: {new Date(preview.sent_at || '').toLocaleString()}
              </span>
              <button className="btn btn-primary btn-sm" onClick={() => setPreview(null)}>Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
